@echo off
echo Stopping any existing Python processes...
taskkill /F /IM python.exe >nul 2>&1
timeout /t 1 >nul

echo Starting NetScope Guardian Backend...
cd backend
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Running main.py...
python main.py
pause
